### ISSUE TITLE
认证和统一异常处理的项目，返回结果为字符串，但是字符串对应的是页面路径情况；就是项目

### ISSUE THREAD

**Issue by gougou1993** [RudeCrab/rude-java#3]
认证和统一异常处理的项目，返回结果为字符串，但是字符串对应的是页面路径情况，就是项目同时包含restful接口和跳转页面的需求，怎么解决？

**Comment by RudeCrab** [comment]
https://github.com/RudeCrab/rude-java/blob/master/project-practice/validation-and-exception-handler2/validation-and-exception-handler2.md
可以看下我写的第二篇文章，对统一处理进行了扩展，你可以按照自己意愿返回数据。

**Comment by gougou1993** [comment]
好的  谢谢
![image](https://user-images.githubusercontent.com/29157454/82520287-5e4fc400-9b56-11ea-9ff3-9371429bdb33.png)
