### ISSUE TITLE
前端代码本地运行不起来

### ISSUE THREAD

**Issue by HTingting** [RudeCrab/rude-java#30]
前端代码拉到本地后，运行不起来；看了下好像是ts的版本问题。但是升级了，解决一部分，与router的使用语法又有冲突。后端代码里面集合的前端代码好像跟前端源码不同步？

**Comment by RudeCrab** [comment]
抱歉，回复慢了
我运行是正常的呢，可能是用的包管理器不一样？
你试试使用 `pnpm` 呢，先使用 `pnpm install`，然后 `pnpm run start`
