### ISSUE TITLE
springsecurity模块ApplicationStartup存在空指针风险

### ISSUE THREAD

**Issue by yark9527** [RudeCrab/rude-java#33]
com.rudecrab.springsecurity.config.ApplicationStartup#getAuthResources()
方法中
`String path = methods.toArray()[0] + ":" + info.getPatternsCondition().getPatterns().toArray()[0];`
报空指针错误，是不是取错了对象，应该是`info.getPathPatternsCondition()`

**Comment by RudeCrab** [comment]
具体是在什么情况下会空指针异常呢，我又测试了一遍，并没有问题。麻烦贴下异常堆栈和接口配置。

**Comment by yark9527** [comment]
![image](https://user-images.githubusercontent.com/24974563/234440706-9e81a5ef-823a-4fab-a9cc-33f4a04f3a00.png)
![image](https://user-images.githubusercontent.com/24974563/234442582-d018e4d5-2c20-4fc5-be1c-dca0c3cfec21.png)
![image](https://user-images.githubusercontent.com/24974563/234441182-8eae5783-8bfa-4eae-abc9-cbdc36aeca6c.png)
另：掘金有给您留言，期待您的回复。

**Comment by yark9527** [comment]
破案了老铁。
是springBoot版本问题导致的。
您使用的版本是2.4.0，我使用的是2.7.10
我版本降级到2.4.0的时候就不会报错了。具体原因正在研究。

**Comment by RudeCrab** [comment]
依赖的大版本更迭是会有些地方变化，但大体一致。clone后不要改动先直接运行吧，这样直观地感受到运行效果后更利于理解和学习
