### ISSUE TITLE
关于Security和rbac两个模块的Filter和Interceptor

### ISSUE THREAD

**Issue by yark9527** [RudeCrab/rude-java#34]
拜读这两个模块的代码之后，发现Security的LoginFilter 和 AuthFilter 与 RBAC模块的LoginInterceptor 和 AuthInterceptor 所实现的功能其实是一样的。
如果我要做实际运用。是不是二取一即可啊？感觉Filter实现的认证和授权更好些。

**Comment by RudeCrab** [comment]
认证授权核心原理和流程就那一套，无论是自己写还是用框架，基本就这些东西。我为了演示自然会将主流的实现方式都写上，不同方式也都隔离了模块进行演示，一个项目/模块里就一种实现方式，在实际运用中选其一种就好。
